sudo: required #permission
services:
  - docker

before_install:
  - docker build -t sami93/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sami93/docker-react npm run test -- --coverage #coverage to exit tests suits