sudo: required #permission
services:
  - docker

before_install:
  - docker build -t sami93/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sami93/docker-react npm run test -- --coverage #coverage to exit tests suits

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-787114486602"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY